[features]
seeds = false
skip-lint = false

[programs.devnet]
solana = "2iPwRfZMtBJroE52FUUV4i5Jm75z18KTm3mJPt2N9ZDZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
