[features]
seeds = false
skip-lint = false

[programs.localnet]
solana = "FkqS1AfpbyAbD9TbguoBZpz6NzGMfbfjpxAZSePW5rFq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
