[features]
seeds = false
skip-lint = false

[programs.localnet]
solana = "FkqS1AfpbyAbD9TbguoBZpz6NzGMfbfjpxAZSePW5rFq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "ts-node tests/solana.ts"
